export const browserListArr=[
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"SoundCloud",
        content:"Music",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"Vimeo",
        content:"Video",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"Quora",
        content:"Social",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"ArtBreeder",
        content:"Art",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"MAGABOOK",
        content:"Social",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"prv.pl",
        content:"Tech",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"Opencollective",
        content:"Finance",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"ok.ur",
        content:"Social",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"Suzuri",
        content:"Business",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"Coroflot",
        content:"Art",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"Flickr",
        content:"Images",
    },
    {
        img:"https://ik.imagekit.io/v4fhgjnfk/image.png?updatedAt=1748987237401",
        name:"Paypal",
        content:"Finance",
    },
]